version: '3'
services:
  hesperides: 
    image: "hesperides/hesperides"
    ports: 
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=fake_mongo,noldap
  gradle-check:
    build:
      context: .
    depends_on:
      - hesperides
    environment:
      - HESPERIDES_HOST=http://hesperides
      - HESPERIDES_PORT=8080
      - HESPERIDES_AUTH=user:password
