version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Running gradle check in Docker image
          command: |
            docker-compose build
            docker-compose run gradle-check
