version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty

    steps:
      - checkout

      - setup_remote_docker:
          version: 17.06.0-ce

      - run:
          name: Install docker-compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      - run:
          name: Running gradle check in Docker image
          command: |
            docker-compose build
            docker-compose run gradle-check
